### ISSUE TITLE
Definições

### ISSUE THREAD

**Issue by alexbruno** [SoftboxLab/moo-cli#1]
Seria legal definirmos algumas coisas básicas.

- qual será o objetivo da CLI
- que problemas ela deve resolver na prática
- seu uso deverá ser através comandos com parâmetros, opções em menu, ambos...
- que recursos ela deve oferecer
- etc...

Comentem abaixo para contribuir.

**Comment by pablohpsilva** [comment]
* Qual sera o objetivo da CLI
  * gerar componentes, telas, servicos/resources, utilitarios e testes atraves de uma CLI. Alterar arquivos ja existentes para adicionar informacoes ou utilitarios;
* Que problemas ela deve resolver na prática?
  * reduzir o tempo de criacao de arquivos simples e complexos;
* seu uso deverá ser através comandos com parâmetros, opções em menu, ambos?
  * ambos. pessoalmente falando, prefiro comandos com parametros.
* Que recursos ela deve oferecer?
  * acredito que dar opcoes de como construir as coisas seria uma boa. Exemplo: quero que a CLI me construa um componente basico pra mim, soh que ele tem ser funcional e tambem deve estar ligado a um flux.

**Comment by alexbruno** [comment]
Acredito que sim. Se entendermos cada comando como um "método" podemos passar os parâmetros que quisermos para cada.

**Comment by pablohpsilva** [comment]
@vilaboim pode demaaaais... :)
