### ISSUE TITLE
Templates TypeScript

### ISSUE THREAD

**Issue by pablohpsilva** [SoftboxLab/moo-cli#18]
Criar Templates TypeScript

**Comment by alexbruno** [comment]
Para Vue e React?
Porque eu não acho que devemos entrar no campo do Angular, a CLI dele já é muito rica em recursos e dificilmente a gente criaria algo que ela já não tenha.

**Comment by pablohpsilva** [comment]
SIm, exatamente :)

**Comment by pablohpsilva** [comment]
Acabei de fazer para React no PR #26

**Comment by alexbruno** [comment]
Vou fazer pra Vue nas próximas alterações quando incrementar os presets.
