### ISSUE TITLE
Iniciar o projeto no moo-cli

### ISSUE THREAD

**Issue by pablohpsilva** [SoftboxLab/moo-cli#2]
Iniciar o projeto no moo-cli.
Deve-se criar um ambiente simples em TS para que possamos trabalhar.

Definir: Usaremos lerna para gerenciar os pacotes/commands que serao criados aqui? issue #3

**Comment by alexbruno** [comment]
Acho que usar Lerna não é uma dependência para iniciar o projeto. Podemos ajustar depois se realmente formos usar.

**Comment by alexbruno** [comment]
Fechando a issue pois já temos mais do que um "Hello World".
