### ISSUE TITLE
Presets @vue/cli

### ISSUE THREAD

**Issue by alexbruno** [SoftboxLab/moo-cli#25]
Criação de projetos @vue/cli já está implementada.
Porém, apenas 2 presets padronizados foram inlcuidos inicialmente:

- **js-stylus-jest-pwa:** Configurações de PWA com JS + Stylus e Jest para testes unitários
- **ts-stylus-jest-pwa:** Mesma coisa mas com Typescript ao invés de JS

Que tal sugerirmos aqui alguns presets que sejam interessantes?

**Comment by pablohpsilva** [comment]
Concordo demais
