### ISSUE TITLE
Lerna

### ISSUE THREAD

**Issue by pablohpsilva** [SoftboxLab/moo-cli#3]
Usaremos lerna para gerenciar os pacotes/commands que serao criados aqui?

**Comment by pablohpsilva** [comment]
Sugestao:
Sim, um para cada programa/command

**Comment by alexbruno** [comment]
Exemplos?

**Comment by pablohpsilva** [comment]
[vue-cli](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue)

**Comment by alexbruno** [comment]
Seria mesmo necessário? Não seriam apenas módulos/comandos da CLI?

**Comment by pablohpsilva** [comment]
Depende do tamanho que vão ficar as coisas. Talvez realmente não precise.
Só quis por na mesa hahahahaha

**Comment by alexbruno** [comment]
Entendi, vamos ouvir o @vilaboim que tem mais XP com Lerna pra termos uma ideia melhor.

**Comment by alexbruno** [comment]
Pela forma como está indo o desenvolvimento até então, pareceu desnecessário o uso de Lerna pois apenas aumentaria a complexidade do projeto sem agregar benefício real.
