### ISSUE TITLE
Preset create-react-app ?

### ISSUE THREAD

**Issue by pablohpsilva** [SoftboxLab/moo-cli#31]
Podemos pensar em usar presets do `create-react-app` ?
Exemplo: `create-react-app my-app --scripts-version=react-scripts-ts` from [Microsoft/TypeScript-React-Starter](https://github.com/Microsoft/TypeScript-React-Starter)

**Comment by alexbruno** [comment]
Bom, eu tenho minhas preferências e não curto muito o `create-react-app`, prefiro uma configuração mais customizada.
Mas acho que quem trabalha mais com React deveria opinar nesse caso.

**Comment by pablohpsilva** [comment]
entao, mas ate onde eu sei tem como voce customizar usando o scripts-version

**Comment by pablohpsilva** [comment]
https://auth0.com/blog/how-to-configure-create-react-app/

**Comment by alexbruno** [comment]
Legal cara! Não conhecia esses recursos ainda.
Acho que podemoos partir nesse rumo então, se você domina eu apoio.
Ficará parecido com o padrão de presets do Vue já implementado.

**Comment by alexbruno** [comment]
De acordo com a discussão [nessa issue](https://github.com/facebook/create-react-app/issues/3480) também é possível apontar um repositório git como alvo do template.
Pode ser uma alternativa para mantermos alguns templates custmizados sem a necessidade de ficar publicando como pacotes NPM.

**Comment by alexbruno** [comment]
Como era uma prioridade, este recurso foi adicionado com 2 presets básicos por enquanto, baseados nos boilerplates do `create-react-app` com as configurações do gandalf-lint.

Após este PR #49 vou gerar uma nova release, pois já temos este e outros recursos relacionados a geração de componentes para lançar.
