### ISSUE TITLE
Need to solve eslint errors on fresh arch project

### ISSUE THREAD

**Issue by alexbruno** [SoftboxLab/moo-cli#41]
Generated code into fresh Vue architecture **shall not pass** by gandalf-lint validation.

**Comment by pablohpsilva** [comment]
I believe the gandalf-lint-vue package is live :) 
Meaning that can be used

**Comment by alexbruno** [comment]
A temporary solution was applied at PR #43

**Comment by pablohpsilva** [comment]
Here it is: https://www.npmjs.com/package/@softboxlab/eslint-config-gandalf-lint-vue
