### ISSUE TITLE
Improve component creation flow

### ISSUE THREAD

**Issue by alexbruno** [SoftboxLab/moo-cli#42]
Check and improve flow of commands to create components.

**Comment by alexbruno** [comment]
Not checked yet, but some problems was reported unsing creation commands.
I will check this ASAP and share any ideas here.

**Comment by pablohpsilva** [comment]
@vilaboim Please close this issue and open a new one with the correct description of what is the bug.

**Comment by vilaboim** [comment]
Closed while there is no evidence.
