### ISSUE TITLE
moo-cli shortcuts

### ISSUE THREAD

**Issue by pablohpsilva** [SoftboxLab/moo-cli#45]
## Explanation
I was wondering if we could create some shortcuts for the cli. Like instead of typing `moo[-cli] <command> <name> <...extras>` we could have something like `mooc <name> <...extras>` for creating components, for example.

## How
I'm not 100% sure on how this could be possible, but I think we could change the `bin` key on the `moo-cli` package.json file to something like this:

```javascript
{
    ...
    bin: {
        moo-cli: "dist/index.js",
        moo: "dist/index.js",
        mooc:"dist/index.js comp",
        mooa: "dist/index.js arch",
        moom: "dist/index.js menu"
    }
    ...
}
```

## Why
Well... Not sure, but at first looked like a good idea.

**Comment by alexbruno** [comment]
Not sure too. I think this can be a little confusing.
