### ISSUE TITLE
Code separation on packages

### ISSUE THREAD

**Issue by pablohpsilva** [SoftboxLab/moo-cli#46]
I would like to suggest that we separate the commands we have on the `moo-cli`, as so as the templates, and utility codes in separate packages.
I don't really know it this is a premature change, but I think we soon will have a huge code on our hands and maybe separating those in packages can be useful in the near future.

**Comment by alexbruno** [comment]
I don't know...
It makes sense if each package will be independent, isolated, turning into different projects.
Automatically, each one will have its own evolution.
Is this we want?
Maybe an improved project architecture can solve this problem.
